apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          # image: ghcr.io/alexandru-braslasu/ci_cd_lab:latest
          image: ghcr.io/alexandru-braslasu/ci_cd_lab@sha256:6f81104f6e9e0c2eb1f1967c327d8ecb799b3fff2871da3b57c6fbf63207fe65
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
